version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
  session:
    image: redis:4.0.14-alpine
    command: redis-server --requirepass test
    hostname: tester
    ports:
      - "6379:6379"
    labels:
      - "mode=standalone"