spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${SPRING_DATASOURCE_MASTER_URL}
      username: ${DATASOURCE_MASTER_USER}
      password: ${DATASOURCE_MASTER_PASSWORD}
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${SPRING_DATASOURCE_SLAVE_URL}
      username: ${DATASOURCE_SLAVE_USER}
      password: ${DATASOURCE_SLAVE_PASSWORD}
  session:
    store-type: redis
  redis:
    host: ${REDIS_MASTER_HOST}
    port: ${REDIS_MASTER_PORT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            threadName: hello
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: true
            dataSource: mydb
            tablePrefix: QRTZ_
            misfireThreshold: 60000
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          dataSource:
            mydb:
              provider: hikaricp
              driver: com.mysql.cj.jdbc.Driver
              URL: ${SPRING_DATASOURCE_MASTER_URL}
              user: ${DATASOURCE_MASTER_USER}
              password: ${DATASOURCE_MASTER_PASSWORD}
              maxConnections: 5
    batch:
      job:
        enabled: true
      jdbc:
        initialize-schema: never

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

ncp:
  storage:
    end-point: https://kr.object.ncloudstorage.com
    region: kr-standard
    access-key: ${NCP_ACCESSKEY}
    secret-key: ${NCP_SECRETKEY}
    bucket: rollingpaperimage