spring:
  servlet:
    multipart:
      max-file-size: 10MB
      location:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mydb
      username: root
      password: ${LOCAL_DB_PASSWORD}
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/mydb
      username: root
      password: ${LOCAL_DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      auto-commit: false
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  mail:
    host: localhost
    port: 1025
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            threadName: hello
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: true
            dataSource: mydb
            tablePrefix: QRTZ_
            misfireThreshold: 60000
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          dataSource:
            mydb:
              provider: hikaricp
              driver: com.mysql.cj.jdbc.Driver
              URL: jdbc:mysql://localhost:3306/mydb
              user: root
              password: ${LOCAL_DB_PASSWORD}
              maxConnections: 5
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

logging:
  level:
    root: debug
  file:
    path:

ncp:
  storage:
    end-point: https://kr.object.ncloudstorage.com
    region: kr-standard
    access-key: ${NCP_ACCESSKEY}
    secret-key: ${NCP_SECRETKEY}
    bucket: rollingpaperimage
