version: '3'
services:
  db:
    image: mysql:8.0.17
    container_name: mysql-master
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - /Users/hoyeonjang/MyProjects/replication/master:/etc/mysql/conf.d
      - /Users/hoyeonjang/MyProjects/replication/masterData:/var/lib/mysql
  db-slave:
    image: mysql:8.0.17
    container_name: mysql-slave
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - /Users/hoyeonjang/MyProjects/replication/slave:/etc/mysql/conf.d
      - /Users/hoyeonjang/MyProjects/replication/slaveData:/var/lib/mysql
    links:
      - db